(() => {
  const stage=document.querySelector('.slide-stage'), promptSlide=stage.querySelector('[data-slide="story-interview-prompt"]'), promptSource=document.getElementById('storyInterviewPrompt'), promptCode=document.createElement('pre');
  promptCode.className='prompt-code-screen';promptCode.tabIndex=0;promptCode.textContent=promptSource.content.textContent.trim().replace(/\n\s*\n/g,'\n');promptSlide.querySelector('.prompt-full').replaceWith(promptCode);promptSlide.querySelector('.overline').textContent='CHATGPT PROMPT';
  stage.querySelector('[data-slide="story-interview-rules"]').remove();stage.querySelector('[data-slide="story-interview-manuscript"]').remove();
  const storyMakingSlides=[stage.querySelector('[data-slide="18"]'),promptSlide], storyAnchor=stage.querySelector('[data-slide="7"]');
  storyMakingSlides.reverse().forEach(slide=>storyAnchor.insertAdjacentElement('afterend',slide));
  const copyButton=document.createElement('button');
  copyButton.type='button';copyButton.id='copyInterviewPrompt';copyButton.className='prompt-copy-action';copyButton.textContent='CHATGPT에 붙여 넣기 · 프롬프트 전체 복사';promptSlide.querySelector('h2').insertAdjacentElement('afterend',copyButton);
  const scenePromptSlide=stage.querySelector('[data-slide="scene-composition-prompt"]'), sceneCopyButton=document.createElement('button');
  sceneCopyButton.type='button';sceneCopyButton.className='prompt-copy-action';sceneCopyButton.textContent='CHATGPT에 붙여 넣기 · 프롬프트 전체 복사';scenePromptSlide.querySelector('h2').insertAdjacentElement('afterend',sceneCopyButton);
  const sceneGenerationSlide=stage.querySelector('[data-slide="scene-generation-prompt"]'), sceneGenerationCopyButton=document.createElement('button');
  sceneGenerationCopyButton.type='button';sceneGenerationCopyButton.className='prompt-copy-action';sceneGenerationCopyButton.textContent='CHATGPT에 붙여 넣기 · 프롬프트 전체 복사';sceneGenerationSlide.querySelector('h2').insertAdjacentElement('afterend',sceneGenerationCopyButton);
  const imagePromptExamples=[
    '평범한 생일날의 집 안 풍경. 엄마가 생일상을 준비하고 있고, 아직 음식이 모두 완성되지 않은 상태에서 생일을 맞은 40대 딸이 집 안에 함께 있다. 가족이 함께 보내는 소박하고 평범한 생일날의 분위기를 표현한다. 생일상과 음식을 중심으로 한 가정적인 공간 구도이며, 특별한 사건이 일어나기 전의 차분한 순간을 보여준다. 원래 이야기의 인물과 공간만 표현하고 새로운 인물이나 사건은 추가하지 않는다.',
    '집 안의 소파에서 80대 아빠가 TV를 보고 있는 장면. 아빠는 평소처럼 무표정한 표정으로 편안하게 소파에 앉아 있다. 딸은 음식이 다 되기를 기다리면서 아빠를 물끄러미 바라보고 있다. 한쪽에서는 엄마가 생일상을 준비하고 있다. 생일날의 평범한 가족 공간과 세 사람의 자연스러운 위치 관계가 잘 드러나도록 구성한다. 아직 특별한 사건은 시작되지 않은 차분한 순간이다.',
    '생일을 맞은 40대 딸이 소파에서 TV를 보고 있는 80대 아빠에게 말을 거는 순간. 딸은 아빠를 바라보며 생일 용돈을 달라는 말을 하고 있고, 아빠는 TV를 보다가 딸 쪽으로 시선을 돌린다. 엄마는 생일상을 준비하고 있는 집 안에 있다. 딸이 먼저 아빠에게 말을 건네면서 평범했던 생일날에 작은 사건이 시작되는 순간을 중심으로 표현한다. 원래 이야기의 집 안 상황을 유지하고 새로운 행동은 추가하지 않는다.',
    '딸의 갑작스러운 용돈 요청을 들은 80대 아빠가 살짝 당황한 순간. 딸은 아빠를 바라보며 웃고 있고, 이어서 “만원만.”이라고 말하는 장면을 표현한다. 아빠는 어떤 금액을 줘야 할지 가늠하기 어려운 듯 잠시 당황한 표정을 보인다. 소파와 TV가 있는 집 안, 생일상을 준비하는 엄마가 함께 보인다. 두 사람의 표정과 시선이 중심이 되는 자연스러운 가족 장면으로 구성한다.',
    '80대 아빠가 딸의 용돈 요청에 너털웃음을 웃으며 외투 안쪽 주머니에 손을 넣는 순간. 아빠가 주머니에서 자신의 비상금 지갑을 꺼내려 하고 있다. 딸은 가까이에서 아빠를 바라보고 있다. 아빠의 외투 안쪽 주머니와 비상금 지갑이 중요한 소품으로 잘 드러나도록 구성한다. 평범한 생일날의 집 안에서 아빠가 딸의 부탁을 흔쾌히 받아들이는 순간을 보여준다.',
    '아빠가 외투 안쪽 주머니에서 꺼낸 비상금 지갑에서 3단으로 곱게 접힌 만 원을 꺼내 딸에게 건네는 장면. 아빠의 손에는 작은 비상금 지갑과 3단으로 곱게 접힌 만 원이 보인다. 딸은 아빠가 건네는 만 원을 받고 있다. 아빠는 딸을 향해 환하게 웃으며 “딸! 생일 축하한다.”라고 말하는 순간이다. 만 원과 두 사람의 손, 아빠의 환한 표정이 이 장면의 핵심이 되도록 구도한다.',
    '아빠에게 만 원을 받은 40대 딸이 아빠를 바라보는 장면. 딸은 자신이 여전히 ‘우리 집 막내’라는 마음을 느끼고 있다. 아빠는 딸에게 만 원을 건넨 뒤 바라보고 있다. 부모님 앞에서 다시 막내가 된 딸의 모습을 중심으로 표현한다. 생일날의 집 안, 아빠의 비상금 지갑과 만 원도 장면에 자연스럽게 보인다. 새로운 사건이나 인물을 추가하지 않고 딸의 현재 모습과 부모님과의 관계를 중심으로 구성한다.',
    '40대가 된 딸이 부모님 앞에서 어른으로 살아온 모습을 보여주는 장면. 부모님을 이끌어가는 어른의 모습과 부모님 앞에서 어리광을 부리지 않게 된 현재의 모습을 표현한다. 구체적인 새로운 사건을 만들지 않고, ‘언제부터인가 부모님 앞에서 어리광을 부리지 않았고 부모님을 이끌어가는 어른의 모습만 있었다’는 원래 이야기의 의미를 시각적으로 보여준다. 부모님과 딸의 관계가 중심이 되는 장면이다.',
    '생일날 아빠에게 만 원을 받은 뒤, 40대 딸이 부모님 앞에서 다시 아이가 된 듯한 모습을 보여주는 장면. 딸과 부모님이 같은 집 안에서 함께 있는 모습이며, 딸은 부모님 앞에서 어른으로만 있을 필요 없이 다시 아이가 될 수 있다는 마음을 느끼고 있다. 부모님 앞에서 다시 아이가 될 수 있어서 행복했던 원래 이야기의 마음을 표현한다. 구체적인 새로운 사건이나 행동은 추가하지 않는다.',
    '평소 무표정한 80대 아빠가 생일날 환하게 웃고 있는 모습을 중심으로 표현한다. 딸은 아빠의 환한 웃음을 바라보고 있다. 아빠의 평소 무표정한 모습과 달리 그날만큼은 환하게 웃고 있다는 점이 잘 드러나도록 한다. 생일날의 집 안 분위기와 두 사람의 자연스러운 거리감을 유지하며, 딸에게 아빠의 웃음이 특별하게 기억되는 장면으로 구성한다.',
    '80대 아빠와 40대 딸이 생일날 함께 정말 많이 웃고 있는 장면. 평소 무표정한 아빠가 환하게 웃고 있고, 딸도 함께 웃고 있다. 딸에게는 ‘가끔은 내가 이렇게 아빠를 웃겨드려야 하는데’라는 마음이 있다. 새로운 사건이나 대사를 추가하지 않고, 아빠의 환한 웃음과 두 사람이 함께 웃었던 기억을 중심으로 표현한다. 집 안의 생일날이라는 원래 공간을 유지한다.',
    '시간이 흘러 다음 해와 그다음 해의 생일 용돈을 받은 모습을 보여주는 장면. 다음 해에는 아빠가 딸에게 2만 원을 건네고, 그다음 해에는 3만 원을 건네는 흐름이 한 장면 안에서 자연스럽게 느껴지도록 구성한다. 매년 생일에 이어진 용돈이라는 원래 이야기의 시간 흐름을 표현한다. 아빠와 딸, 생일날의 가족 공간, 용돈이라는 중요한 사물을 중심으로 보여준다. 새로운 사건이나 인물은 추가하지 않는다.',
    '3만 원을 받은 뒤 더 이상 생일 용돈을 받을 수 없게 된 이야기의 변화를 보여주는 장면. 구체적인 새로운 사건이나 이유를 만들지 않고, 이전까지 이어지던 생일 용돈이 여기서 멈추었다는 시간의 흐름을 표현한다. 아빠와 딸의 관계와 생일이라는 맥락은 유지하되, 원래 이야기에서 말하지 않은 상황이나 행동은 추가하지 않는다. 조용한 전환점처럼 표현한다.',
    '40대 딸의 기억 속에 오래 남아 있는 생일날의 만 원과 아빠의 모습을 표현한다. 아빠의 비상금 지갑에서 나온 3단으로 곱게 접힌 만 원이 중요한 중심 사물로 보인다. 그 만 원을 건네주던 아빠와 그날 환하게 웃던 아빠의 모습이 딸의 기억 속에 남아 있다. 실제 이야기에서 중요한 비상금 지갑, 곱게 접힌 만 원, 아빠의 환한 웃음을 중심으로 구성하고 새로운 사건은 추가하지 않는다.',
    '40대가 된 딸과 부모님을 함께 보여주는 마지막 장면. 딸은 어른이 되었지만 부모님 앞에서는 언제까지나 막내딸이고 싶은 마음을 가지고 있다. 이야기 전체를 통해 기억에 남은 3단으로 곱게 접힌 만 원과 그날 환하게 웃던 아빠의 모습이 마지막 기억으로 남아 있다. 새로운 사건이나 행동을 만들지 않고, 원래 이야기의 마지막 마음인 ‘부모님 앞에서는 언제까지나 막내딸이고 싶구나’를 중심으로 조용하고 따뜻하게 마무리한다.',
    '글 없이 삽화만. 빈 소파 앞에서 3단으로 접힌 만 원을 쥔 미미의 뒷모습을 보여준다. 생일 용돈의 기억과 아빠를 향한 마음이 조용히 남는 마지막 장면으로 구성한다. 새로운 인물이나 사건은 추가하지 않는다.'
  ];
  const imageExampleSlides=[];for(let group=0;group<8;group++){const section=document.createElement('section'),headingId=`imagePromptExample${group+1}`,items=imagePromptExamples.slice(group*2,group*2+2);section.className='slide example-slide image-prompt-example-slide';section.dataset.slide=`image-prompt-example-${group+1}`;section.setAttribute('aria-labelledby',headingId);section.innerHTML=`<p class="example-label">프롬프트 답변 예시 · 『미미의 생일 만원』</p><h2 id="${headingId}">이미지 생성 프롬프트 ${group+1} / 8</h2><div class="image-prompt-grid"></div>`;const grid=section.querySelector('.image-prompt-grid');items.forEach((prompt,offset)=>{const article=document.createElement('article'),title=document.createElement('b'),label=document.createElement('strong'),copy=document.createElement('p');title.textContent=`장면 ${group*2+offset+1}｜${group*2+offset+1}~${group*2+offset+2}페이지`;label.textContent='[이미지 프롬프트]';copy.textContent=prompt;article.append(title,label,copy);grid.append(article);});imageExampleSlides.push(section);}
  imageExampleSlides.reverse().forEach(slide=>sceneGenerationSlide.insertAdjacentElement('afterend',slide));
  stage.querySelectorAll('.image-prompt-grid article').forEach((article,index)=>{const sceneNumber=index+1;article.querySelector('b').textContent=`장면 ${sceneNumber}｜${sceneNumber*2-1}~${sceneNumber*2}페이지`;});
  const sceneTexts=[
    ['1~2','“미미야, 생선조림 해놨어!”\n오늘은 미미 생일!\n미미는 쪼르르 달려갔어요.','엄마가 생일상을 준비하는 부엌 쪽으로 미미가 달려갑니다. 아직 음식이 다 되지 않은 따뜻한 집 안의 생일 분위기를 보여줍니다.'],['3~4','소파엔 아빠가 앉아 있어요.\n텔레비전만 보고 있는 아빠.\n미미는 물끄러미 바라봤어요.','소파에서 TV를 보는 아빠와 그를 바라보는 미미를 보여줍니다. 엄마는 뒤에서 생일상을 준비하고 있습니다.'],['5~6','문득, 응석 부리고 싶어졌어요.','아빠를 바라보던 미미의 얼굴에 어린아이 같은 마음이 조용히 떠오르는 순간을 보여줍니다.'],['7~8','“하지 마세요!”\n“왜 그러셨어요?”\n어느새 미미는, 어른처럼 말하는 딸이 되어 있었어요.','미미가 아빠를 걱정하며 어른처럼 말하고 챙기는 일상의 모습을 보여줍니다.'],['9~10','아빠는 나이가 많이 드셨어요.\n이젠 미미가 먼저,\n아빠 대신 정해드려요.','나이 든 아빠 앞에서 미미가 먼저 살피고 결정하는 모습을 보여줍니다.'],['11~12','“아빠, 오늘 나 생일인 거 알지?”\n“그럼, 알지! 생일 축하한다.”','미미가 소파의 아빠에게 생일을 묻고, 아빠가 딸을 향해 축하를 건네는 모습을 보여줍니다.'],['13~14','“그럼… 나 생일 용돈 주세요.”\n아빠 눈이 동그래졌어요.','미미의 뜻밖의 말에 아빠의 눈이 동그래지고, 미미는 아빠를 바라봅니다.'],['15~16','“얼마를 줘야 하지?”\n아빠는 턱을 만지작만지작.','아빠가 잠시 턱을 만지작거리며 생각하고, 미미는 그 모습을 기다립니다.'],['17~18','“딱 만 원만 줘요.\n다 컸어도, 용돈 받고 싶어요.”','미미가 웃으며 만 원만 달라고 말하고, 아빠는 그 말을 듣습니다.'],['19~20','아빠 얼굴이 활짝!\n안주머니 속, 작은 지갑을 꺼냈어요.','환하게 웃는 아빠가 안주머니에서 작은 비상금 지갑을 꺼냅니다.'],['21~22','꼬깃꼬깃 접힌 만 원 한 장,\n미미 손에 살포시.','아빠가 지갑에서 3단으로 곱게 접힌 만 원을 꺼내 미미 손에 건넵니다.'],['23~24','정말 오랜만이에요,\n아빠한테 용돈 받는 거.','만 원을 받아 든 미미의 모습과, 딸을 바라보는 아빠의 다정한 순간을 보여줍니다.'],['25~26','‘나는 아직도, 아빠 앞에선 아기구나.’\n미미 눈가가 촉촉해졌어요.','만 원을 든 미미의 눈가가 촉촉해지고, 부모님 앞에서 다시 아이가 된 마음을 보여줍니다.'],['27~28','“아빠, 고마워요!\n내년에도 주세요, 하하하!”','미미와 아빠가 환하게 웃습니다. 생일상과 가족의 따뜻한 분위기를 함께 보여줍니다.'],['29~30','그 뒤로 삼 년,\n생일 용돈은 계속되었어요.\n조금씩, 아주 조금씩.','시간이 흐르며 이어진 세 번의 생일을 보여줍니다. 생일 용돈이 조금씩 늘어나는 흐름을 담습니다.'],['31~32','글 없음','빈 소파 앞에서 접힌 만 원을 쥔 미미의 뒷모습만 삽화로 보여줍니다.']
  ];
  sceneTexts[3][2]='〈과거 회상 장면〉\n미미가 아빠를 걱정하며 어른처럼 말하고 챙기는 일상을, 현재와 구분되는 과거 회상 같은 톤으로 구성합니다.';
  sceneTexts[8][1]='“만 원만”';
  sceneTexts[11][1]='와~~ 용돈 받았다!!';
  stage.querySelectorAll('[data-slide^="scene-plan-"]').forEach(slide=>slide.remove());
  const sceneTextSlides=[];for(let group=0;group<8;group++){const section=document.createElement('section'),headingId=`sceneTextPlan${group+1}`,items=sceneTexts.slice(group*2,group*2+2);section.className='slide example-slide scene-text-plan-slide';section.dataset.slide=`scene-text-plan-${group+1}`;section.setAttribute('aria-labelledby',headingId);section.innerHTML=`<p class="example-label">프롬프트 답변 예시 · 『미미의 생일 만원』</p><h2 id="${headingId}">16개 펼침 장면 구성 ${group+1} / 8</h2><div class="scene-text-grid"></div>`;const grid=section.querySelector('.scene-text-grid');items.forEach(([pages,copy,art],offset)=>{const article=document.createElement('article'),title=document.createElement('b'),pageBlock=document.createElement('div'),pageLabel=document.createElement('strong'),pageText=document.createElement('p'),artBlock=document.createElement('div'),artLabel=document.createElement('strong'),artText=document.createElement('p');title.textContent=`장면 ${group*2+offset+1}｜${pages}페이지`;pageLabel.textContent='페이지 글';pageText.textContent=copy;artLabel.textContent='그림 장면';artText.textContent=art;pageBlock.append(pageLabel,pageText);artBlock.append(artLabel,artText);article.append(title,pageBlock,artBlock);grid.append(article);});sceneTextSlides.push(section);}
  sceneTextSlides.reverse().forEach(slide=>scenePromptSlide.insertAdjacentElement('afterend',slide));
  const slides=[...document.querySelectorAll('.slide')], prev=document.getElementById('prevButton'), next=document.getElementById('nextButton'), current=document.getElementById('currentSlide'), total=document.getElementById('totalSlides'), progress=document.getElementById('progressBar'), fullscreen=document.getElementById('fullscreenButton'), print=document.getElementById('printButton'), copyPrompt=document.getElementById('copyInterviewPrompt');
  let index=0, timer=0, snapshot=null;
  const matched=location.hash.match(/slide=(\d+)/); if(matched) index=Math.min(Math.max(+matched[1]-1,0),slides.length-1);
  slides.forEach(slide=>{slide.dataset.revealIndex='0'; slide.querySelectorAll('.reveal-step').forEach(step=>{step.dataset.fullText=step.textContent.trim();if(step.dataset.revealMode!=='block')step.textContent='';step.classList.add('is-pending');});});
  const finish=()=>{clearTimeout(timer);const step=document.querySelector('.reveal-step.is-typing');if(step){step.textContent=step.dataset.fullText;step.classList.remove('is-typing');step.classList.add('is-visible');}};
  function reveal(step){finish();step.classList.remove('is-pending');if(step.dataset.revealMode==='block'){step.classList.add('is-visible');return;}let at=0;const text=step.dataset.fullText;step.classList.add('is-visible','is-typing');function type(){at++;step.textContent=text.slice(0,at);if(at<text.length)timer=setTimeout(type,18);else step.classList.remove('is-typing');}type();}
  function reset(slide){slide.dataset.revealIndex='0';slide.querySelectorAll('.reveal-step').forEach(step=>{if(step.dataset.revealMode!=='block')step.textContent='';step.classList.remove('is-visible','is-typing');step.classList.add('is-pending');});}
  function showAll(slide){const steps=[...slide.querySelectorAll('.reveal-step')];steps.forEach(step=>{if(step.dataset.revealMode!=='block')step.textContent=step.dataset.fullText;step.classList.remove('is-pending','is-typing');step.classList.add('is-visible');});slide.dataset.revealIndex=String(steps.length);}
  function show(at,hash=true,complete=false){finish();index=Math.min(Math.max(at,0),slides.length-1);slides.forEach((slide,i)=>{const active=i===index;slide.classList.toggle('is-active',active);slide.setAttribute('aria-hidden',String(!active));if(!active)reset(slide);});if(complete)showAll(slides[index]);current.textContent=index+1;total.textContent=slides.length;progress.style.width=`${(index+1)/slides.length*100}%`;prev.disabled=index===0;next.disabled=index===slides.length-1&&!slides[index].querySelector('.is-pending');document.title=`${index+1}/${slides.length} · 나도 그림동화책 작가 3주차`;if(hash)history.replaceState(null,'',`#slide=${index+1}`);}
  function forward(){const slide=slides[index],steps=[...slide.querySelectorAll('.reveal-step')],at=+slide.dataset.revealIndex;if(slide.querySelector('.is-typing')){finish();return;}if(at<steps.length){reveal(steps[at]);slide.dataset.revealIndex=at+1;return;}show(index+1);}
  prev.onclick=()=>index&&show(index-1,true,true);next.onclick=forward;document.addEventListener('keydown',e=>{if(['ArrowRight','PageDown','Enter',' '].includes(e.key)){e.preventDefault();forward();}else if(['ArrowLeft','PageUp','Backspace'].includes(e.key)){e.preventDefault();index&&show(index-1,true,true);}else if(e.key==='Home')show(0);else if(e.key==='End')show(slides.length-1);else if(e.key.toLowerCase()==='f')fullscreen.click();});
  copyPrompt?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(promptSource.content.textContent.trim());copyPrompt.textContent='프롬프트를 복사했습니다';setTimeout(()=>{copyPrompt.textContent='이야기 인터뷰 프롬프트 복사';},1800);}catch{copyPrompt.textContent='복사에 실패했습니다';}});
  sceneCopyButton.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(scenePromptSlide.querySelector('.prompt-code-screen').textContent.trim());sceneCopyButton.textContent='프롬프트를 복사했습니다';setTimeout(()=>{sceneCopyButton.textContent='CHATGPT에 붙여 넣기 · 프롬프트 전체 복사';},1800);}catch{sceneCopyButton.textContent='복사에 실패했습니다';}});
  sceneGenerationCopyButton.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(sceneGenerationSlide.querySelector('.prompt-code-screen').textContent.trim());sceneGenerationCopyButton.textContent='프롬프트를 복사했습니다';setTimeout(()=>{sceneGenerationCopyButton.textContent='CHATGPT에 붙여 넣기 · 프롬프트 전체 복사';},1800);}catch{sceneGenerationCopyButton.textContent='복사에 실패했습니다';}});
  fullscreen.onclick=async()=>{if(!document.fullscreenElement)await document.documentElement.requestFullscreen?.();else await document.exitFullscreen?.();};document.addEventListener('fullscreenchange',()=>{const active=!!document.fullscreenElement;document.body.classList.toggle('is-fullscreen',active);fullscreen.textContent=active?'전체화면 종료':'전체화면';});
  function beforePrint(){if(snapshot)return;snapshot=slides.map(slide=>[slide.dataset.revealIndex,...[...slide.querySelectorAll('.reveal-step')].map(step=>[step.textContent,step.className])]);slides.forEach(showAll);}function afterPrint(){if(!snapshot)return;slides.forEach((slide,i)=>{slide.dataset.revealIndex=snapshot[i][0];[...slide.querySelectorAll('.reveal-step')].forEach((step,j)=>{[step.textContent,step.className]=snapshot[i][j+1];});});snapshot=null;}print.onclick=()=>{beforePrint();window.print();};addEventListener('beforeprint',beforePrint);addEventListener('afterprint',afterPrint);addEventListener('hashchange',()=>{const hash=location.hash.match(/slide=(\d+)/);if(hash)show(+hash[1]-1,false);});show(index);
})();
