(() => {
  const slides=[...document.querySelectorAll('.slide')], prev=document.getElementById('prevButton'), next=document.getElementById('nextButton'), current=document.getElementById('currentSlide'), total=document.getElementById('totalSlides'), progress=document.getElementById('progressBar'), fullscreen=document.getElementById('fullscreenButton'), print=document.getElementById('printButton');
  let index=0, timer=0, snapshot=null;
  const matched=location.hash.match(/slide=(\d+)/); if(matched) index=Math.min(Math.max(+matched[1]-1,0),slides.length-1);
  slides.forEach(slide=>{slide.dataset.revealIndex='0'; slide.querySelectorAll('.reveal-step').forEach(step=>{step.dataset.fullText=step.textContent.trim();step.textContent='';step.classList.add('is-pending');});});
  const finish=()=>{clearTimeout(timer);const step=document.querySelector('.reveal-step.is-typing');if(step){step.textContent=step.dataset.fullText;step.classList.remove('is-typing');step.classList.add('is-visible');}};
  function reveal(step){finish();let at=0;const text=step.dataset.fullText;step.classList.remove('is-pending');step.classList.add('is-visible','is-typing');function type(){at++;step.textContent=text.slice(0,at);if(at<text.length)timer=setTimeout(type,18);else step.classList.remove('is-typing');}type();}
  function reset(slide){slide.dataset.revealIndex='0';slide.querySelectorAll('.reveal-step').forEach(step=>{step.textContent='';step.classList.remove('is-visible','is-typing');step.classList.add('is-pending');});}
  function showAll(slide){const steps=[...slide.querySelectorAll('.reveal-step')];steps.forEach(step=>{step.textContent=step.dataset.fullText;step.classList.remove('is-pending','is-typing');step.classList.add('is-visible');});slide.dataset.revealIndex=String(steps.length);}
  function show(at,hash=true,complete=false){finish();index=Math.min(Math.max(at,0),slides.length-1);slides.forEach((slide,i)=>{const active=i===index;slide.classList.toggle('is-active',active);slide.setAttribute('aria-hidden',String(!active));if(!active)reset(slide);});if(complete)showAll(slides[index]);current.textContent=index+1;total.textContent=slides.length;progress.style.width=`${(index+1)/slides.length*100}%`;prev.disabled=index===0;next.disabled=index===slides.length-1&&!slides[index].querySelector('.is-pending');document.title=`${index+1}/${slides.length} · 나도 그림동화책 작가 3주차`;if(hash)history.replaceState(null,'',`#slide=${index+1}`);}
  function forward(){const slide=slides[index],steps=[...slide.querySelectorAll('.reveal-step')],at=+slide.dataset.revealIndex;if(slide.querySelector('.is-typing')){finish();return;}if(at<steps.length){reveal(steps[at]);slide.dataset.revealIndex=at+1;return;}show(index+1);}
  prev.onclick=()=>index&&show(index-1,true,true);next.onclick=forward;document.addEventListener('keydown',e=>{if(['ArrowRight','PageDown','Enter',' '].includes(e.key)){e.preventDefault();forward();}else if(['ArrowLeft','PageUp','Backspace'].includes(e.key)){e.preventDefault();index&&show(index-1,true,true);}else if(e.key==='Home')show(0);else if(e.key==='End')show(slides.length-1);else if(e.key.toLowerCase()==='f')fullscreen.click();});
  fullscreen.onclick=async()=>{if(!document.fullscreenElement)await document.documentElement.requestFullscreen?.();else await document.exitFullscreen?.();};document.addEventListener('fullscreenchange',()=>{const active=!!document.fullscreenElement;document.body.classList.toggle('is-fullscreen',active);fullscreen.textContent=active?'전체화면 종료':'전체화면';});
  function beforePrint(){if(snapshot)return;snapshot=slides.map(slide=>[slide.dataset.revealIndex,...[...slide.querySelectorAll('.reveal-step')].map(step=>[step.textContent,step.className])]);slides.forEach(showAll);}function afterPrint(){if(!snapshot)return;slides.forEach((slide,i)=>{slide.dataset.revealIndex=snapshot[i][0];[...slide.querySelectorAll('.reveal-step')].forEach((step,j)=>{[step.textContent,step.className]=snapshot[i][j+1];});});snapshot=null;}print.onclick=()=>{beforePrint();window.print();};addEventListener('beforeprint',beforePrint);addEventListener('afterprint',afterPrint);addEventListener('hashchange',()=>{const hash=location.hash.match(/slide=(\d+)/);if(hash)show(+hash[1]-1,false);});show(index);
})();
